version: "3.2"
services:
  neo4j:
    image: neo4j:latest
    container_name: 'devneo4j'
    volumes:
      - './data:/data'
      - './logs:/logs'
      - './import:/var/lib/neo4j/import'
      - './conf/:/conf/'
      - './plugins/:/plugins/'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
        - neo4j_go_net
    command: neo4j

networks:
  neo4j_go_net:
    driver: bridge

volumes:
  dgraph:
